import type { Metadata } from "next";
import Link from "next/link";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

export const metadata: Metadata = {
  title: "Wyszukiwanie globalne | Dlugomat",
  description: "Globalna wyszukiwarka spraw, dokumentow, orzeczen, klientow i ustawien.",
};

const tabs = [
  { name: "Wszystko", count: 124 },
  { name: "Sprawy", count: 42 },
  { name: "Dokumenty", count: 38 },
  { name: "Orzeczenia", count: 28 },
  { name: "Klienci", count: 12 },
  { name: "Ustawienia", count: 4 },
];

const results = [
  { kind: "Sprawa", title: "KAN/2026/0418 - Alfa Sp. z o.o.", excerpt: "Pozew o zaplate 420 000 PLN. Najblizsza rozprawa 14.05.2026 w SO Warszawa, sala 304.", href: "/panel/sprawa/KAN-2026-0418", time: "11.05.2026 09:24" },
  { kind: "Dokument", title: "Pozew - Alfa Sp. z o.o. (wersja 3)", excerpt: "Ostatnia edycja: mec. Kowalska. Status: do podpisu. Generated by AI assistant on 10.05.2026.", href: "/panel/dokumenty/PIS-2026-0418", time: "10.05.2026 17:42" },
  { kind: "Orzeczenie", title: "III CZP 11/26 - Sad Najwyzszy", excerpt: "Skutki zawezwania do proby ugodowej dla biegu przedawnienia roszczen. Trafnosc 96%.", href: "/panel/baza-orzecznicza/III-CZP-11-26", time: "08.05.2026" },
  { kind: "Klient", title: "Alfa Sp. z o.o. - karta klienta", excerpt: "8 spraw, wartosc portfela 1 240 000 PLN, opiekun: Anna Nowak. Klient od 2022.", href: "/panel/klienci/KL-001", time: "ostatnia zmiana: 09.05.2026" },
  { kind: "Sprawa", title: "W-2026-0418 - postepowanie windykacyjne", excerpt: "Etap windykacji, DPD 124. Przekazano do kancelarii Kruk w dniu 02.05.2026.", href: "/panel/sprawa/W-2026-0418", time: "08.05.2026 12:14" },
  { kind: "Dokument", title: "Wezwanie do zaplaty (szablon)", excerpt: "Szablon pisma przedsadowego z 412 uzyciami. Ostatnia aktualizacja regulacyjna 02.2026.", href: "/panel/dokumenty/szablon-wezwanie", time: "02.02.2026" },
  { kind: "Ustawienia", title: "Powiadomienia MFA", excerpt: "Konfiguracja drugiego skladnika logowania. Obecnie aktywne: aplikacja TOTP i klucz sprzetowy.", href: "/panel/ustawienia/bezpieczenstwo", time: "07.04.2026" },
];

const kindTone: Record<string, "neutral" | "info" | "success" | "warning" | "danger"> = {
  Sprawa: "info",
  Dokument: "neutral",
  Orzeczenie: "info",
  Klient: "neutral",
  Ustawienia: "neutral",
};

export default function SzukajPage() {
  return (
    <div className="space-y-8 px-6 py-8 lg:px-10">
      <header className="space-y-3">
        <Badge tone="info" withDot>
          Wyszukiwanie globalne
        </Badge>
        <h1 className="font-display text-3xl text-dlugomat-900">Znajdz co potrzebujesz</h1>
        <p className="max-w-2xl text-sm text-dlugomat-600">
          Przeszukaj wszystkie zasoby Dlugomat w jednym miejscu - sprawy, dokumenty, baze orzecznicza,
          klientow i ustawienia. Wyszukiwarka rozumie skroty branzowe i sygnatury sadowe.
        </p>
      </header>

      <Card elevation="pop" className="p-6">
        <label htmlFor="global-search" className="sr-only">
          Szukaj
        </label>
        <input
          id="global-search"
          type="search"
          placeholder="Wpisz fraze, sygnature, nazwe klienta lub numer sprawy..."
          className="w-full rounded-md border border-dlugomat-200 px-4 py-3 text-base focus-visible:shadow-shield-focus"
        />
        <div className="mt-3 flex flex-wrap items-center justify-between gap-2 text-xs text-dlugomat-500">
          <span>Wskazowki: uzyj cudzyslowu dla frazy, prefiksu &quot;sprawa:&quot; lub &quot;klient:&quot;</span>
          <span>Skroty klawiaturowe: Ctrl+K aby otworzyc, Esc aby zamknac</span>
        </div>
      </Card>

      <section aria-label="Filtry kategorii">
        <div className="flex flex-wrap items-center gap-2">
          {tabs.map((t, i) => (
            <button
              key={t.name}
              type="button"
              className={`flex items-center gap-2 rounded-full px-4 py-1.5 text-xs font-medium transition ${
                i === 0 ? "bg-dlugomat-900 text-white" : "bg-dlugomat-50 text-dlugomat-700 hover:bg-dlugomat-100"
              }`}
            >
              {t.name}
              <span
                className={`rounded-full px-2 py-0.5 text-[10px] font-mono ${
                  i === 0 ? "bg-white/20" : "bg-white text-dlugomat-500"
                }`}
              >
                {t.count}
              </span>
            </button>
          ))}
        </div>
      </section>

      <section aria-label="Wyniki wyszukiwania" className="space-y-3">
        {results.map((r) => (
          <Card key={r.href} elevation="subtle" className="p-5">
            <div className="flex items-start gap-4">
              <Badge tone={kindTone[r.kind] ?? "neutral"}>{r.kind}</Badge>
              <div className="flex-1">
                <Link href={r.href} className="font-display text-base text-dlugomat-900 hover:underline">
                  {r.title}
                </Link>
                <p className="mt-1 text-sm text-dlugomat-600">{r.excerpt}</p>
                <p className="mt-2 font-mono text-xs text-dlugomat-500">{r.time}</p>
              </div>
              <Button variant="ghost" size="sm" asChild>
                <Link href={r.href}>Otworz</Link>
              </Button>
            </div>
          </Card>
        ))}
      </section>
    </div>
  );
}
